version: '2'
services:
  fluent:
    image: docker.io/ledangtuanbk/fluent:1.2
    container_name: fluent
    volumes:
      - ./etc:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
